### ISSUE TITLE
Battery Research overlapping other research projects

### ISSUE THREAD

**Issue by Delta7x** [Stolij/Rimworld-More_Batteries#2]
Basically the title. Installed the mod and found that the research for the new batteries overlaps research from the base game.
https://i.imgur.com/71NWlWH.png

Disabled all mods but the More Batteries mod and started a new colony to find the issue still persisted.
https://i.imgur.com/OLgyjcd.png

Could the research for More Batteries be organized elsewhere on the tree or added in a separate tab similar to other mods?

**Comment by Stolij** [comment]
Closing this issue, since the research projects belonging to this mod have been moved into their own tab.
